version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: LeadManagement.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000
      - ConnectionStrings__DefaultConnection=Server=db,1433;Database=LeadManagementDb;User Id=sa;Password=Your_password123!;
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - leadnet

  frontend:
    build:
      context: ./frontend/lead-management-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://localhost:5000/api
    networks:
      - leadnet

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - SA_PASSWORD=Your_password123!
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
    volumes:
      - mssqldata:/var/opt/mssql
    networks:
      - leadnet

volumes:
  mssqldata:

networks:
  leadnet: